// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hydfs.proto
#ifndef GRPC_hydfs_2eproto__INCLUDED
#define GRPC_hydfs_2eproto__INCLUDED

#include "hydfs.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace filetransfer {

class FileTransferService final {
 public:
  static constexpr char const* service_full_name() {
    return "filetransfer.FileTransferService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status FileExists(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::filetransfer::FileExistsStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::FileExistsStatus>> AsyncFileExists(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::FileExistsStatus>>(AsyncFileExistsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::FileExistsStatus>> PrepareAsyncFileExists(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::FileExistsStatus>>(PrepareAsyncFileExistsRaw(context, request, cq));
    }
    virtual ::grpc::Status CreateFileLeader(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::filetransfer::OperationStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>> AsyncCreateFileLeader(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>>(AsyncCreateFileLeaderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>> PrepareAsyncCreateFileLeader(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>>(PrepareAsyncCreateFileLeaderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriterInterface< ::filetransfer::FileChunk>> AppendFile(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::filetransfer::FileChunk>>(AppendFileRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>> AsyncAppendFile(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>>(AsyncAppendFileRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>> PrepareAsyncAppendFile(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>>(PrepareAsyncAppendFileRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderInterface< ::filetransfer::FileChunk>> GetFile(::grpc::ClientContext* context, const ::filetransfer::GetRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::filetransfer::FileChunk>>(GetFileRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::filetransfer::FileChunk>> AsyncGetFile(::grpc::ClientContext* context, const ::filetransfer::GetRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::filetransfer::FileChunk>>(AsyncGetFileRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::filetransfer::FileChunk>> PrepareAsyncGetFile(::grpc::ClientContext* context, const ::filetransfer::GetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::filetransfer::FileChunk>>(PrepareAsyncGetFileRaw(context, request, cq));
    }
    virtual ::grpc::Status MergeFile(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::filetransfer::OperationStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>> AsyncMergeFile(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>>(AsyncMergeFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>> PrepareAsyncMergeFile(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>>(PrepareAsyncMergeFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriterInterface< ::filetransfer::FileChunk>> OverwriteFile(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::filetransfer::FileChunk>>(OverwriteFileRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>> AsyncOverwriteFile(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>>(AsyncOverwriteFileRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>> PrepareAsyncOverwriteFile(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>>(PrepareAsyncOverwriteFileRaw(context, response, cq));
    }
    virtual ::grpc::Status ForwardLeaderFiles(::grpc::ClientContext* context, const ::filetransfer::ForwardRequest& request, ::filetransfer::OperationStatus* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>> AsyncForwardLeaderFiles(::grpc::ClientContext* context, const ::filetransfer::ForwardRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>>(AsyncForwardLeaderFilesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>> PrepareAsyncForwardLeaderFiles(::grpc::ClientContext* context, const ::filetransfer::ForwardRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>>(PrepareAsyncForwardLeaderFilesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void FileExists(::grpc::ClientContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::FileExistsStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FileExists(::grpc::ClientContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::FileExistsStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void CreateFileLeader(::grpc::ClientContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::OperationStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CreateFileLeader(::grpc::ClientContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::OperationStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void AppendFile(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::ClientWriteReactor< ::filetransfer::FileChunk>* reactor) = 0;
      virtual void GetFile(::grpc::ClientContext* context, const ::filetransfer::GetRequest* request, ::grpc::ClientReadReactor< ::filetransfer::FileChunk>* reactor) = 0;
      virtual void MergeFile(::grpc::ClientContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::OperationStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void MergeFile(::grpc::ClientContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::OperationStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void OverwriteFile(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::ClientWriteReactor< ::filetransfer::FileChunk>* reactor) = 0;
      virtual void ForwardLeaderFiles(::grpc::ClientContext* context, const ::filetransfer::ForwardRequest* request, ::filetransfer::OperationStatus* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ForwardLeaderFiles(::grpc::ClientContext* context, const ::filetransfer::ForwardRequest* request, ::filetransfer::OperationStatus* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::FileExistsStatus>* AsyncFileExistsRaw(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::FileExistsStatus>* PrepareAsyncFileExistsRaw(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>* AsyncCreateFileLeaderRaw(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>* PrepareAsyncCreateFileLeaderRaw(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::filetransfer::FileChunk>* AppendFileRaw(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>* AsyncAppendFileRaw(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>* PrepareAsyncAppendFileRaw(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::filetransfer::FileChunk>* GetFileRaw(::grpc::ClientContext* context, const ::filetransfer::GetRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::filetransfer::FileChunk>* AsyncGetFileRaw(::grpc::ClientContext* context, const ::filetransfer::GetRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::filetransfer::FileChunk>* PrepareAsyncGetFileRaw(::grpc::ClientContext* context, const ::filetransfer::GetRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>* AsyncMergeFileRaw(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>* PrepareAsyncMergeFileRaw(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::filetransfer::FileChunk>* OverwriteFileRaw(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>* AsyncOverwriteFileRaw(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>* PrepareAsyncOverwriteFileRaw(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>* AsyncForwardLeaderFilesRaw(::grpc::ClientContext* context, const ::filetransfer::ForwardRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::filetransfer::OperationStatus>* PrepareAsyncForwardLeaderFilesRaw(::grpc::ClientContext* context, const ::filetransfer::ForwardRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status FileExists(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::filetransfer::FileExistsStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::FileExistsStatus>> AsyncFileExists(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::FileExistsStatus>>(AsyncFileExistsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::FileExistsStatus>> PrepareAsyncFileExists(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::FileExistsStatus>>(PrepareAsyncFileExistsRaw(context, request, cq));
    }
    ::grpc::Status CreateFileLeader(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::filetransfer::OperationStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>> AsyncCreateFileLeader(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>>(AsyncCreateFileLeaderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>> PrepareAsyncCreateFileLeader(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>>(PrepareAsyncCreateFileLeaderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::filetransfer::FileChunk>> AppendFile(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::filetransfer::FileChunk>>(AppendFileRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>> AsyncAppendFile(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>>(AsyncAppendFileRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>> PrepareAsyncAppendFile(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>>(PrepareAsyncAppendFileRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::filetransfer::FileChunk>> GetFile(::grpc::ClientContext* context, const ::filetransfer::GetRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::filetransfer::FileChunk>>(GetFileRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::filetransfer::FileChunk>> AsyncGetFile(::grpc::ClientContext* context, const ::filetransfer::GetRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::filetransfer::FileChunk>>(AsyncGetFileRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::filetransfer::FileChunk>> PrepareAsyncGetFile(::grpc::ClientContext* context, const ::filetransfer::GetRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::filetransfer::FileChunk>>(PrepareAsyncGetFileRaw(context, request, cq));
    }
    ::grpc::Status MergeFile(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::filetransfer::OperationStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>> AsyncMergeFile(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>>(AsyncMergeFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>> PrepareAsyncMergeFile(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>>(PrepareAsyncMergeFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::filetransfer::FileChunk>> OverwriteFile(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::filetransfer::FileChunk>>(OverwriteFileRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>> AsyncOverwriteFile(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>>(AsyncOverwriteFileRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>> PrepareAsyncOverwriteFile(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>>(PrepareAsyncOverwriteFileRaw(context, response, cq));
    }
    ::grpc::Status ForwardLeaderFiles(::grpc::ClientContext* context, const ::filetransfer::ForwardRequest& request, ::filetransfer::OperationStatus* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>> AsyncForwardLeaderFiles(::grpc::ClientContext* context, const ::filetransfer::ForwardRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>>(AsyncForwardLeaderFilesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>> PrepareAsyncForwardLeaderFiles(::grpc::ClientContext* context, const ::filetransfer::ForwardRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>>(PrepareAsyncForwardLeaderFilesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void FileExists(::grpc::ClientContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::FileExistsStatus* response, std::function<void(::grpc::Status)>) override;
      void FileExists(::grpc::ClientContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::FileExistsStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
      void CreateFileLeader(::grpc::ClientContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::OperationStatus* response, std::function<void(::grpc::Status)>) override;
      void CreateFileLeader(::grpc::ClientContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::OperationStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AppendFile(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::ClientWriteReactor< ::filetransfer::FileChunk>* reactor) override;
      void GetFile(::grpc::ClientContext* context, const ::filetransfer::GetRequest* request, ::grpc::ClientReadReactor< ::filetransfer::FileChunk>* reactor) override;
      void MergeFile(::grpc::ClientContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::OperationStatus* response, std::function<void(::grpc::Status)>) override;
      void MergeFile(::grpc::ClientContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::OperationStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
      void OverwriteFile(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::ClientWriteReactor< ::filetransfer::FileChunk>* reactor) override;
      void ForwardLeaderFiles(::grpc::ClientContext* context, const ::filetransfer::ForwardRequest* request, ::filetransfer::OperationStatus* response, std::function<void(::grpc::Status)>) override;
      void ForwardLeaderFiles(::grpc::ClientContext* context, const ::filetransfer::ForwardRequest* request, ::filetransfer::OperationStatus* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::filetransfer::FileExistsStatus>* AsyncFileExistsRaw(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::filetransfer::FileExistsStatus>* PrepareAsyncFileExistsRaw(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>* AsyncCreateFileLeaderRaw(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>* PrepareAsyncCreateFileLeaderRaw(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::filetransfer::FileChunk>* AppendFileRaw(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response) override;
    ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>* AsyncAppendFileRaw(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>* PrepareAsyncAppendFileRaw(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::filetransfer::FileChunk>* GetFileRaw(::grpc::ClientContext* context, const ::filetransfer::GetRequest& request) override;
    ::grpc::ClientAsyncReader< ::filetransfer::FileChunk>* AsyncGetFileRaw(::grpc::ClientContext* context, const ::filetransfer::GetRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::filetransfer::FileChunk>* PrepareAsyncGetFileRaw(::grpc::ClientContext* context, const ::filetransfer::GetRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>* AsyncMergeFileRaw(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>* PrepareAsyncMergeFileRaw(::grpc::ClientContext* context, const ::filetransfer::FileRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::filetransfer::FileChunk>* OverwriteFileRaw(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response) override;
    ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>* AsyncOverwriteFileRaw(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>* PrepareAsyncOverwriteFileRaw(::grpc::ClientContext* context, ::filetransfer::OperationStatus* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>* AsyncForwardLeaderFilesRaw(::grpc::ClientContext* context, const ::filetransfer::ForwardRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::filetransfer::OperationStatus>* PrepareAsyncForwardLeaderFilesRaw(::grpc::ClientContext* context, const ::filetransfer::ForwardRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_FileExists_;
    const ::grpc::internal::RpcMethod rpcmethod_CreateFileLeader_;
    const ::grpc::internal::RpcMethod rpcmethod_AppendFile_;
    const ::grpc::internal::RpcMethod rpcmethod_GetFile_;
    const ::grpc::internal::RpcMethod rpcmethod_MergeFile_;
    const ::grpc::internal::RpcMethod rpcmethod_OverwriteFile_;
    const ::grpc::internal::RpcMethod rpcmethod_ForwardLeaderFiles_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status FileExists(::grpc::ServerContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::FileExistsStatus* response);
    virtual ::grpc::Status CreateFileLeader(::grpc::ServerContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::OperationStatus* response);
    virtual ::grpc::Status AppendFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::filetransfer::FileChunk>* reader, ::filetransfer::OperationStatus* response);
    virtual ::grpc::Status GetFile(::grpc::ServerContext* context, const ::filetransfer::GetRequest* request, ::grpc::ServerWriter< ::filetransfer::FileChunk>* writer);
    virtual ::grpc::Status MergeFile(::grpc::ServerContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::OperationStatus* response);
    virtual ::grpc::Status OverwriteFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::filetransfer::FileChunk>* reader, ::filetransfer::OperationStatus* response);
    virtual ::grpc::Status ForwardLeaderFiles(::grpc::ServerContext* context, const ::filetransfer::ForwardRequest* request, ::filetransfer::OperationStatus* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_FileExists : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FileExists() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_FileExists() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileExists(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::FileExistsStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFileExists(::grpc::ServerContext* context, ::filetransfer::FileRequest* request, ::grpc::ServerAsyncResponseWriter< ::filetransfer::FileExistsStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateFileLeader : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateFileLeader() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_CreateFileLeader() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFileLeader(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateFileLeader(::grpc::ServerContext* context, ::filetransfer::FileRequest* request, ::grpc::ServerAsyncResponseWriter< ::filetransfer::OperationStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AppendFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AppendFile() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_AppendFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::filetransfer::FileChunk>* /*reader*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAppendFile(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::filetransfer::OperationStatus, ::filetransfer::FileChunk>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(2, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetFile() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_GetFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFile(::grpc::ServerContext* /*context*/, const ::filetransfer::GetRequest* /*request*/, ::grpc::ServerWriter< ::filetransfer::FileChunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFile(::grpc::ServerContext* context, ::filetransfer::GetRequest* request, ::grpc::ServerAsyncWriter< ::filetransfer::FileChunk>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(3, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_MergeFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_MergeFile() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_MergeFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MergeFile(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMergeFile(::grpc::ServerContext* context, ::filetransfer::FileRequest* request, ::grpc::ServerAsyncResponseWriter< ::filetransfer::OperationStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_OverwriteFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OverwriteFile() {
      ::grpc::Service::MarkMethodAsync(5);
    }
    ~WithAsyncMethod_OverwriteFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OverwriteFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::filetransfer::FileChunk>* /*reader*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOverwriteFile(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::filetransfer::OperationStatus, ::filetransfer::FileChunk>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(5, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ForwardLeaderFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ForwardLeaderFiles() {
      ::grpc::Service::MarkMethodAsync(6);
    }
    ~WithAsyncMethod_ForwardLeaderFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardLeaderFiles(::grpc::ServerContext* /*context*/, const ::filetransfer::ForwardRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestForwardLeaderFiles(::grpc::ServerContext* context, ::filetransfer::ForwardRequest* request, ::grpc::ServerAsyncResponseWriter< ::filetransfer::OperationStatus>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_FileExists<WithAsyncMethod_CreateFileLeader<WithAsyncMethod_AppendFile<WithAsyncMethod_GetFile<WithAsyncMethod_MergeFile<WithAsyncMethod_OverwriteFile<WithAsyncMethod_ForwardLeaderFiles<Service > > > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_FileExists : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FileExists() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::filetransfer::FileRequest, ::filetransfer::FileExistsStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::FileExistsStatus* response) { return this->FileExists(context, request, response); }));}
    void SetMessageAllocatorFor_FileExists(
        ::grpc::MessageAllocator< ::filetransfer::FileRequest, ::filetransfer::FileExistsStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::filetransfer::FileRequest, ::filetransfer::FileExistsStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FileExists() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileExists(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::FileExistsStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FileExists(
      ::grpc::CallbackServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::FileExistsStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_CreateFileLeader : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateFileLeader() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::filetransfer::FileRequest, ::filetransfer::OperationStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::OperationStatus* response) { return this->CreateFileLeader(context, request, response); }));}
    void SetMessageAllocatorFor_CreateFileLeader(
        ::grpc::MessageAllocator< ::filetransfer::FileRequest, ::filetransfer::OperationStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::filetransfer::FileRequest, ::filetransfer::OperationStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CreateFileLeader() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFileLeader(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateFileLeader(
      ::grpc::CallbackServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AppendFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AppendFile() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackClientStreamingHandler< ::filetransfer::FileChunk, ::filetransfer::OperationStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, ::filetransfer::OperationStatus* response) { return this->AppendFile(context, response); }));
    }
    ~WithCallbackMethod_AppendFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::filetransfer::FileChunk>* /*reader*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::filetransfer::FileChunk>* AppendFile(
      ::grpc::CallbackServerContext* /*context*/, ::filetransfer::OperationStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetFile() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackServerStreamingHandler< ::filetransfer::GetRequest, ::filetransfer::FileChunk>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::filetransfer::GetRequest* request) { return this->GetFile(context, request); }));
    }
    ~WithCallbackMethod_GetFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFile(::grpc::ServerContext* /*context*/, const ::filetransfer::GetRequest* /*request*/, ::grpc::ServerWriter< ::filetransfer::FileChunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::filetransfer::FileChunk>* GetFile(
      ::grpc::CallbackServerContext* /*context*/, const ::filetransfer::GetRequest* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_MergeFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_MergeFile() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::filetransfer::FileRequest, ::filetransfer::OperationStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::filetransfer::FileRequest* request, ::filetransfer::OperationStatus* response) { return this->MergeFile(context, request, response); }));}
    void SetMessageAllocatorFor_MergeFile(
        ::grpc::MessageAllocator< ::filetransfer::FileRequest, ::filetransfer::OperationStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::filetransfer::FileRequest, ::filetransfer::OperationStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_MergeFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MergeFile(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* MergeFile(
      ::grpc::CallbackServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_OverwriteFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_OverwriteFile() {
      ::grpc::Service::MarkMethodCallback(5,
          new ::grpc::internal::CallbackClientStreamingHandler< ::filetransfer::FileChunk, ::filetransfer::OperationStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, ::filetransfer::OperationStatus* response) { return this->OverwriteFile(context, response); }));
    }
    ~WithCallbackMethod_OverwriteFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OverwriteFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::filetransfer::FileChunk>* /*reader*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::filetransfer::FileChunk>* OverwriteFile(
      ::grpc::CallbackServerContext* /*context*/, ::filetransfer::OperationStatus* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ForwardLeaderFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ForwardLeaderFiles() {
      ::grpc::Service::MarkMethodCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::filetransfer::ForwardRequest, ::filetransfer::OperationStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::filetransfer::ForwardRequest* request, ::filetransfer::OperationStatus* response) { return this->ForwardLeaderFiles(context, request, response); }));}
    void SetMessageAllocatorFor_ForwardLeaderFiles(
        ::grpc::MessageAllocator< ::filetransfer::ForwardRequest, ::filetransfer::OperationStatus>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(6);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::filetransfer::ForwardRequest, ::filetransfer::OperationStatus>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ForwardLeaderFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardLeaderFiles(::grpc::ServerContext* /*context*/, const ::filetransfer::ForwardRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ForwardLeaderFiles(
      ::grpc::CallbackServerContext* /*context*/, const ::filetransfer::ForwardRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_FileExists<WithCallbackMethod_CreateFileLeader<WithCallbackMethod_AppendFile<WithCallbackMethod_GetFile<WithCallbackMethod_MergeFile<WithCallbackMethod_OverwriteFile<WithCallbackMethod_ForwardLeaderFiles<Service > > > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_FileExists : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FileExists() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_FileExists() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileExists(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::FileExistsStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_CreateFileLeader : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateFileLeader() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_CreateFileLeader() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFileLeader(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AppendFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AppendFile() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_AppendFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::filetransfer::FileChunk>* /*reader*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetFile() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_GetFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFile(::grpc::ServerContext* /*context*/, const ::filetransfer::GetRequest* /*request*/, ::grpc::ServerWriter< ::filetransfer::FileChunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_MergeFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_MergeFile() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_MergeFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MergeFile(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_OverwriteFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OverwriteFile() {
      ::grpc::Service::MarkMethodGeneric(5);
    }
    ~WithGenericMethod_OverwriteFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OverwriteFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::filetransfer::FileChunk>* /*reader*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ForwardLeaderFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ForwardLeaderFiles() {
      ::grpc::Service::MarkMethodGeneric(6);
    }
    ~WithGenericMethod_ForwardLeaderFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardLeaderFiles(::grpc::ServerContext* /*context*/, const ::filetransfer::ForwardRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_FileExists : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FileExists() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_FileExists() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileExists(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::FileExistsStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFileExists(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateFileLeader : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateFileLeader() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_CreateFileLeader() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFileLeader(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateFileLeader(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AppendFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AppendFile() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_AppendFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::filetransfer::FileChunk>* /*reader*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAppendFile(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(2, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetFile() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_GetFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFile(::grpc::ServerContext* /*context*/, const ::filetransfer::GetRequest* /*request*/, ::grpc::ServerWriter< ::filetransfer::FileChunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(3, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_MergeFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_MergeFile() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_MergeFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MergeFile(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMergeFile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_OverwriteFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OverwriteFile() {
      ::grpc::Service::MarkMethodRaw(5);
    }
    ~WithRawMethod_OverwriteFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OverwriteFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::filetransfer::FileChunk>* /*reader*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOverwriteFile(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(5, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ForwardLeaderFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ForwardLeaderFiles() {
      ::grpc::Service::MarkMethodRaw(6);
    }
    ~WithRawMethod_ForwardLeaderFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardLeaderFiles(::grpc::ServerContext* /*context*/, const ::filetransfer::ForwardRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestForwardLeaderFiles(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(6, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FileExists : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FileExists() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FileExists(context, request, response); }));
    }
    ~WithRawCallbackMethod_FileExists() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileExists(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::FileExistsStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FileExists(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateFileLeader : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateFileLeader() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateFileLeader(context, request, response); }));
    }
    ~WithRawCallbackMethod_CreateFileLeader() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFileLeader(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CreateFileLeader(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AppendFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AppendFile() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->AppendFile(context, response); }));
    }
    ~WithRawCallbackMethod_AppendFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AppendFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::filetransfer::FileChunk>* /*reader*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* AppendFile(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetFile() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->GetFile(context, request); }));
    }
    ~WithRawCallbackMethod_GetFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFile(::grpc::ServerContext* /*context*/, const ::filetransfer::GetRequest* /*request*/, ::grpc::ServerWriter< ::filetransfer::FileChunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* GetFile(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_MergeFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_MergeFile() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->MergeFile(context, request, response); }));
    }
    ~WithRawCallbackMethod_MergeFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MergeFile(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* MergeFile(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_OverwriteFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_OverwriteFile() {
      ::grpc::Service::MarkMethodRawCallback(5,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->OverwriteFile(context, response); }));
    }
    ~WithRawCallbackMethod_OverwriteFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OverwriteFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::filetransfer::FileChunk>* /*reader*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* OverwriteFile(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ForwardLeaderFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ForwardLeaderFiles() {
      ::grpc::Service::MarkMethodRawCallback(6,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ForwardLeaderFiles(context, request, response); }));
    }
    ~WithRawCallbackMethod_ForwardLeaderFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ForwardLeaderFiles(::grpc::ServerContext* /*context*/, const ::filetransfer::ForwardRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ForwardLeaderFiles(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FileExists : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FileExists() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::filetransfer::FileRequest, ::filetransfer::FileExistsStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::filetransfer::FileRequest, ::filetransfer::FileExistsStatus>* streamer) {
                       return this->StreamedFileExists(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FileExists() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FileExists(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::FileExistsStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFileExists(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::filetransfer::FileRequest,::filetransfer::FileExistsStatus>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateFileLeader : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateFileLeader() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::filetransfer::FileRequest, ::filetransfer::OperationStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::filetransfer::FileRequest, ::filetransfer::OperationStatus>* streamer) {
                       return this->StreamedCreateFileLeader(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateFileLeader() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateFileLeader(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateFileLeader(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::filetransfer::FileRequest,::filetransfer::OperationStatus>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_MergeFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_MergeFile() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::filetransfer::FileRequest, ::filetransfer::OperationStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::filetransfer::FileRequest, ::filetransfer::OperationStatus>* streamer) {
                       return this->StreamedMergeFile(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_MergeFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status MergeFile(::grpc::ServerContext* /*context*/, const ::filetransfer::FileRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMergeFile(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::filetransfer::FileRequest,::filetransfer::OperationStatus>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ForwardLeaderFiles : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ForwardLeaderFiles() {
      ::grpc::Service::MarkMethodStreamed(6,
        new ::grpc::internal::StreamedUnaryHandler<
          ::filetransfer::ForwardRequest, ::filetransfer::OperationStatus>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::filetransfer::ForwardRequest, ::filetransfer::OperationStatus>* streamer) {
                       return this->StreamedForwardLeaderFiles(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ForwardLeaderFiles() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ForwardLeaderFiles(::grpc::ServerContext* /*context*/, const ::filetransfer::ForwardRequest* /*request*/, ::filetransfer::OperationStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedForwardLeaderFiles(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::filetransfer::ForwardRequest,::filetransfer::OperationStatus>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_FileExists<WithStreamedUnaryMethod_CreateFileLeader<WithStreamedUnaryMethod_MergeFile<WithStreamedUnaryMethod_ForwardLeaderFiles<Service > > > > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_GetFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_GetFile() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::filetransfer::GetRequest, ::filetransfer::FileChunk>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::filetransfer::GetRequest, ::filetransfer::FileChunk>* streamer) {
                       return this->StreamedGetFile(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_GetFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetFile(::grpc::ServerContext* /*context*/, const ::filetransfer::GetRequest* /*request*/, ::grpc::ServerWriter< ::filetransfer::FileChunk>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedGetFile(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::filetransfer::GetRequest,::filetransfer::FileChunk>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_GetFile<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_FileExists<WithStreamedUnaryMethod_CreateFileLeader<WithSplitStreamingMethod_GetFile<WithStreamedUnaryMethod_MergeFile<WithStreamedUnaryMethod_ForwardLeaderFiles<Service > > > > > StreamedService;
};

}  // namespace filetransfer


#endif  // GRPC_hydfs_2eproto__INCLUDED
