// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hydfs.proto

#include "hydfs.pb.h"
#include "hydfs.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace filetransfer {

static const char* FileTransferService_method_names[] = {
  "/filetransfer.FileTransferService/CreateFile",
  "/filetransfer.FileTransferService/GetFile",
  "/filetransfer.FileTransferService/AppendFile",
};

std::unique_ptr< FileTransferService::Stub> FileTransferService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FileTransferService::Stub> stub(new FileTransferService::Stub(channel, options));
  return stub;
}

FileTransferService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateFile_(FileTransferService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_GetFile_(FileTransferService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_AppendFile_(FileTransferService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientWriter< ::filetransfer::FileChunk>* FileTransferService::Stub::CreateFileRaw(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response) {
  return ::grpc::internal::ClientWriterFactory< ::filetransfer::FileChunk>::Create(channel_.get(), rpcmethod_CreateFile_, context, response);
}

void FileTransferService::Stub::async::CreateFile(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response, ::grpc::ClientWriteReactor< ::filetransfer::FileChunk>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::filetransfer::FileChunk>::Create(stub_->channel_.get(), stub_->rpcmethod_CreateFile_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>* FileTransferService::Stub::AsyncCreateFileRaw(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::filetransfer::FileChunk>::Create(channel_.get(), cq, rpcmethod_CreateFile_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>* FileTransferService::Stub::PrepareAsyncCreateFileRaw(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::filetransfer::FileChunk>::Create(channel_.get(), cq, rpcmethod_CreateFile_, context, response, false, nullptr);
}

::grpc::ClientReader< ::filetransfer::FileChunk>* FileTransferService::Stub::GetFileRaw(::grpc::ClientContext* context, const ::filetransfer::DownloadRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::filetransfer::FileChunk>::Create(channel_.get(), rpcmethod_GetFile_, context, request);
}

void FileTransferService::Stub::async::GetFile(::grpc::ClientContext* context, const ::filetransfer::DownloadRequest* request, ::grpc::ClientReadReactor< ::filetransfer::FileChunk>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::filetransfer::FileChunk>::Create(stub_->channel_.get(), stub_->rpcmethod_GetFile_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::filetransfer::FileChunk>* FileTransferService::Stub::AsyncGetFileRaw(::grpc::ClientContext* context, const ::filetransfer::DownloadRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::filetransfer::FileChunk>::Create(channel_.get(), cq, rpcmethod_GetFile_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::filetransfer::FileChunk>* FileTransferService::Stub::PrepareAsyncGetFileRaw(::grpc::ClientContext* context, const ::filetransfer::DownloadRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::filetransfer::FileChunk>::Create(channel_.get(), cq, rpcmethod_GetFile_, context, request, false, nullptr);
}

::grpc::ClientWriter< ::filetransfer::FileChunk>* FileTransferService::Stub::AppendFileRaw(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response) {
  return ::grpc::internal::ClientWriterFactory< ::filetransfer::FileChunk>::Create(channel_.get(), rpcmethod_AppendFile_, context, response);
}

void FileTransferService::Stub::async::AppendFile(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response, ::grpc::ClientWriteReactor< ::filetransfer::FileChunk>* reactor) {
  ::grpc::internal::ClientCallbackWriterFactory< ::filetransfer::FileChunk>::Create(stub_->channel_.get(), stub_->rpcmethod_AppendFile_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>* FileTransferService::Stub::AsyncAppendFileRaw(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::filetransfer::FileChunk>::Create(channel_.get(), cq, rpcmethod_AppendFile_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>* FileTransferService::Stub::PrepareAsyncAppendFileRaw(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncWriterFactory< ::filetransfer::FileChunk>::Create(channel_.get(), cq, rpcmethod_AppendFile_, context, response, false, nullptr);
}

FileTransferService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileTransferService_method_names[0],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< FileTransferService::Service, ::filetransfer::FileChunk, ::filetransfer::UploadStatus>(
          [](FileTransferService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::filetransfer::FileChunk>* reader,
             ::filetransfer::UploadStatus* resp) {
               return service->CreateFile(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileTransferService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< FileTransferService::Service, ::filetransfer::DownloadRequest, ::filetransfer::FileChunk>(
          [](FileTransferService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::filetransfer::DownloadRequest* req,
             ::grpc::ServerWriter<::filetransfer::FileChunk>* writer) {
               return service->GetFile(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileTransferService_method_names[2],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< FileTransferService::Service, ::filetransfer::FileChunk, ::filetransfer::UploadStatus>(
          [](FileTransferService::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReader<::filetransfer::FileChunk>* reader,
             ::filetransfer::UploadStatus* resp) {
               return service->AppendFile(ctx, reader, resp);
             }, this)));
}

FileTransferService::Service::~Service() {
}

::grpc::Status FileTransferService::Service::CreateFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::filetransfer::FileChunk>* reader, ::filetransfer::UploadStatus* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileTransferService::Service::GetFile(::grpc::ServerContext* context, const ::filetransfer::DownloadRequest* request, ::grpc::ServerWriter< ::filetransfer::FileChunk>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileTransferService::Service::AppendFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::filetransfer::FileChunk>* reader, ::filetransfer::UploadStatus* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace filetransfer

