// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hydfs.proto
#ifndef GRPC_hydfs_2eproto__INCLUDED
#define GRPC_hydfs_2eproto__INCLUDED

#include "hydfs.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace filetransfer {

class FileTransferService final {
 public:
  static constexpr char const* service_full_name() {
    return "filetransfer.FileTransferService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientWriterInterface< ::filetransfer::FileChunk>> CreateFile(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::filetransfer::FileChunk>>(CreateFileRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>> AsyncCreateFile(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>>(AsyncCreateFileRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>> PrepareAsyncCreateFile(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>>(PrepareAsyncCreateFileRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CreateFile(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response, ::grpc::ClientWriteReactor< ::filetransfer::FileChunk>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::filetransfer::FileChunk>* CreateFileRaw(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>* AsyncCreateFileRaw(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::filetransfer::FileChunk>* PrepareAsyncCreateFileRaw(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::filetransfer::FileChunk>> CreateFile(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::filetransfer::FileChunk>>(CreateFileRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>> AsyncCreateFile(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>>(AsyncCreateFileRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>> PrepareAsyncCreateFile(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>>(PrepareAsyncCreateFileRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CreateFile(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response, ::grpc::ClientWriteReactor< ::filetransfer::FileChunk>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::filetransfer::FileChunk>* CreateFileRaw(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response) override;
    ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>* AsyncCreateFileRaw(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::filetransfer::FileChunk>* PrepareAsyncCreateFileRaw(::grpc::ClientContext* context, ::filetransfer::UploadStatus* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CreateFile_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CreateFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::filetransfer::FileChunk>* reader, ::filetransfer::UploadStatus* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateFile() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CreateFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::filetransfer::FileChunk>* /*reader*/, ::filetransfer::UploadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateFile(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::filetransfer::UploadStatus, ::filetransfer::FileChunk>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CreateFile<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CreateFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CreateFile() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::filetransfer::FileChunk, ::filetransfer::UploadStatus>(
            [this](
                   ::grpc::CallbackServerContext* context, ::filetransfer::UploadStatus* response) { return this->CreateFile(context, response); }));
    }
    ~WithCallbackMethod_CreateFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::filetransfer::FileChunk>* /*reader*/, ::filetransfer::UploadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::filetransfer::FileChunk>* CreateFile(
      ::grpc::CallbackServerContext* /*context*/, ::filetransfer::UploadStatus* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CreateFile<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CreateFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateFile() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CreateFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::filetransfer::FileChunk>* /*reader*/, ::filetransfer::UploadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateFile() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CreateFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::filetransfer::FileChunk>* /*reader*/, ::filetransfer::UploadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateFile(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CreateFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CreateFile() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->CreateFile(context, response); }));
    }
    ~WithRawCallbackMethod_CreateFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::filetransfer::FileChunk>* /*reader*/, ::filetransfer::UploadStatus* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* CreateFile(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace filetransfer


#endif  // GRPC_hydfs_2eproto__INCLUDED
